import React from 'react'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import UserProvider from './contexts/UserContext'
import ProductsProvider from './contexts/ProductsContext'
import CartProvider from './contexts/CartContext'
import Header from './components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' className='bg-gray-300'>
			<UserProvider>
				<ProductsProvider>
					<CartProvider>
						<body className={inter.className}>
							<Header />
							{children}
						</body>
					</CartProvider>
				</ProductsProvider>
			</UserProvider>
		</html>
	)
}
