version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: boschiadm
      POSTGRES_DB: boschidb
    ports:
      - 5432:5432
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5433:5433
    depends_on:
      - db
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend